title: Zhineng Jin's Homepage
page-top-title: Zhineng Jin
top-section-bg-text: Civil Engineering
home-subtitle: Zhineng Jin&ensp;|&ensp;金治能
copyright-text: '&copy; Zhineng Jin 2023-2025. All Rights Reserved.'
